/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/shared/AboutView.vue')['default']
    Button: typeof import('./src/components/shared/Button.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    DonutChart: typeof import('./src/components/statistics/DonutChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeSpace: typeof import('./src/components/HomeSpace.vue')['default']
    InfoData: typeof import('./src/components/statistics/InfoData.vue')['default']
    IngreseConApple: typeof import('./src/components/login/IngreseConApple.vue')['default']
    IngreseConFacebook: typeof import('./src/components/login/IngreseConFacebook.vue')['default']
    IngreseConGoolge: typeof import('./src/components/login/IngreseConGoolge.vue')['default']
    InitHomeSpace: typeof import('./src/components/InitHomeSpace.vue')['default']
    InputTexto: typeof import('./src/components/shared/InputTexto.vue')['default']
    LineChart: typeof import('./src/components/statistics/LineChart.vue')['default']
    LinkButton: typeof import('./src/components/home/LinkButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Sidebar: typeof import('./src/components/home/SidebarComponent.vue')['default']
    SideBar: typeof import('primevue/sidebar')['default']
    SidebarComponent: typeof import('./src/components/home/SidebarComponent.vue')['default']
    SplashView: typeof import('./src/components/shared/SplashView.vue')['default']
    StatisticFilter: typeof import('./src/components/statistics/StatisticFilter.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
